### ValueSet $expand: diagnose-seite
# @name expand-diagnose-seite
GET http://localhost:8080/ValueSet/diagnose-seite/$expand
Authorization: Basic basic:secret

### $validate-code valid: L
# @name validate-valid-1-diagnose-seite
GET http://localhost:8080/ValueSet/$validate-code
    ?url=https://fhir.cognovis.de/praxis/ValueSet/diagnose-seite
    &system=https://fhir.cognovis.de/praxis/CodeSystem/diagnose-seite
    &code=L
Authorization: Basic basic:secret

### $validate-code valid: R
# @name validate-valid-2-diagnose-seite
GET http://localhost:8080/ValueSet/$validate-code
    ?url=https://fhir.cognovis.de/praxis/ValueSet/diagnose-seite
    &system=https://fhir.cognovis.de/praxis/CodeSystem/diagnose-seite
    &code=R
Authorization: Basic basic:secret

### $validate-code invalid: INVALID_XYZ
# @name validate-invalid-diagnose-seite
GET http://localhost:8080/ValueSet/$validate-code
    ?url=https://fhir.cognovis.de/praxis/ValueSet/diagnose-seite
    &system=https://fhir.cognovis.de/praxis/CodeSystem/diagnose-seite
    &code=INVALID_XYZ
Authorization: Basic basic:secret
