### ValueSet: Genehmigung Typ - $expand
# @name expand
GET {{baseUrl}}/ValueSet/genehmigung-typ/$expand
Authorization: Basic basic:secret

### ValueSet: Genehmigung Typ - $validate-code valid (kopfbezogen)
# @name validate_valid_1
GET {{baseUrl}}/ValueSet/genehmigung-typ/$validate-code?system=https://fhir.cognovis.de/praxis/CodeSystem/genehmigung-typ&code=kopfbezogen
Authorization: Basic basic:secret

### ValueSet: Genehmigung Typ - $validate-code valid (betriebsstaette)
# @name validate_valid_2
GET {{baseUrl}}/ValueSet/genehmigung-typ/$validate-code?system=https://fhir.cognovis.de/praxis/CodeSystem/genehmigung-typ&code=betriebsstaette
Authorization: Basic basic:secret

### ValueSet: Genehmigung Typ - $validate-code invalid
# @name validate_invalid
GET {{baseUrl}}/ValueSet/genehmigung-typ/$validate-code?system=https://fhir.cognovis.de/praxis/CodeSystem/genehmigung-typ&code=INVALID_CODE_XYZ
Authorization: Basic basic:secret
