### ValueSet $expand: scheinart
# @name expand-scheinart
GET http://localhost:8080/ValueSet/scheinart/$expand
Authorization: Basic basic:secret

### $validate-code valid: gkv
# @name validate-valid-1-scheinart
GET http://localhost:8080/ValueSet/$validate-code
    ?url=https://fhir.cognovis.de/praxis/ValueSet/scheinart
    &system=https://fhir.cognovis.de/praxis/CodeSystem/scheinart
    &code=gkv
Authorization: Basic basic:secret

### $validate-code valid: pkv
# @name validate-valid-2-scheinart
GET http://localhost:8080/ValueSet/$validate-code
    ?url=https://fhir.cognovis.de/praxis/ValueSet/scheinart
    &system=https://fhir.cognovis.de/praxis/CodeSystem/scheinart
    &code=pkv
Authorization: Basic basic:secret

### $validate-code invalid: INVALID_XYZ
# @name validate-invalid-scheinart
GET http://localhost:8080/ValueSet/$validate-code
    ?url=https://fhir.cognovis.de/praxis/ValueSet/scheinart
    &system=https://fhir.cognovis.de/praxis/CodeSystem/scheinart
    &code=INVALID_XYZ
Authorization: Basic basic:secret
