### CodeSystem: einwilligung-kategorie - Valid code: dsgvo
# @name valid_dsgvo
GET {{baseUrl}}/Concept?system=https://fhir.cognovis.de/praxis/CodeSystem/einwilligung-kategorie&code=dsgvo
Authorization: Basic basic:secret

### CodeSystem: einwilligung-kategorie - Valid code: dmp
# @name valid_dmp
GET {{baseUrl}}/Concept?system=https://fhir.cognovis.de/praxis/CodeSystem/einwilligung-kategorie&code=dmp
Authorization: Basic basic:secret

### CodeSystem: einwilligung-kategorie - Invalid code
# @name invalid
GET {{baseUrl}}/Concept?system=https://fhir.cognovis.de/praxis/CodeSystem/einwilligung-kategorie&code=INVALID_CODE_XYZ
Authorization: Basic basic:secret
